name: Release - CSS (standalone)

permissions:
  contents: write

on:
  push:
    tags:
      - 'css-?v[0-9]+*'

jobs:
  # Create the Github Release™ so the packages have something to be uploaded to
  create-release:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - id: create-release
        run: |
          # Create the Github Release™
          gh release create ${{ github.ref_name }} --draft
          echo "created announcement!"
  build-css:
    needs: [create-release]
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - id: build-css
        run: |
          cd oranda-css
          yarn install
          # Run tailwind build
          yarn run build
          ls dist
          echo "built css!"
          # Upload css to the Github Release™
          gh release upload ${{ github.ref_name }} dist/oranda.css
          echo "uploaded css!"
  publish-release:
    runs-on: ubuntu-latest
    needs: [build-css]
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: mark release as non-draft
        run: |
          gh release edit ${{ github.ref_name }} --draft=false
